### ISSUE TITLE
Bug BBQ: Image rendering in Lesson 02

### ISSUE THREAD

**Issue by hec8855** [datacarpentry/python-ecology-lesson#244] opened 2018-02-20 19:30 UTC
The two images under 'Extracting Range based Subsets: Slicing' have superscripts denoting indexes which do not correctly render to fit the image.

**Comment by hec8855** [comment] 2018-02-20 19:31
![screen shot 2018-02-20 at 1 31 12 pm](https://user-images.githubusercontent.com/13354605/36444985-67f6cecc-1642-11e8-9ce4-9884b814a147.png)

**Comment by wrightaprilm** [comment] 2018-02-20 22:54
I'm not seeing this issue on FireFox or Safari on Mac (High Sierra). Could you let us know what platform you're using so I can replicate the issue?

**Comment by trallard** [comment] 2018-02-21 12:12
Same here, checked in Safari and Chrome (Windows and Mac) and could not reproduce the issue.

<img width="636" alt="screen shot 2018-02-21 at 12 08 44" src="https://user-images.githubusercontent.com/23552331/36479283-04a6188c-1700-11e8-80a7-6056a6052fd9.png">

**Comment by djennewe** [comment] 2018-03-21 19:56
I'm able to replicate the problem on Internet Explorer 11 and Microsoft Edge 41 on Windows 10 64 bit.

**Comment by djennewe** [comment] 2018-03-21 19:58
![python-img-ie](https://user-images.githubusercontent.com/17789352/37734122-4023f770-2d18-11e8-801e-03e07c7d7f87.PNG)
Internet Explorer 11

**Comment by djennewe** [comment] 2018-03-21 19:58
![python-img-msedge](https://user-images.githubusercontent.com/17789352/37734131-4ada7342-2d18-11e8-815f-82fd1286efdc.PNG)
MS Edge 41

**Comment by wrightaprilm** [comment] 2018-04-05 18:39
I am genuinely unsure what is causing this. I'm tagging it as open for the Bug BBQ.

**Comment by katrintirok** [comment] 2018-04-12 20:06
It may be solved by using .png files for the graphs instead of .svg files. Could also try to export all objects as paths in the .svg, but not sure whether this would solve it.

**Comment by wrightaprilm** [comment] 2018-04-13 16:46
Addressed in #263.

**Closed by wrightaprilm** 2018-04-13 16:46 UTC
Labels: help wanted, high priority, type:formatting
