### ISSUE TITLE
Solution code in episode 06 (ggplot) not rendered as code

### ISSUE THREAD

**Issue by colinmorris** [datacarpentry/python-ecology-lesson#267] opened 2018-04-17 20:13 UTC
In [this lesson](http://www.datacarpentry.org/python-ecology-lesson/06-visualization-ggplot-python/) the solution code isn't styled as a code block (i.e. not monospace, no grey background).

**Comment by tmorrell** [comment] 2018-04-24 21:08
Should be fixed in #271

**Comment by wrightaprilm** [comment] 2018-04-25 02:34
The issue is persisting, but I'm going to close this issue, and have us manage the discussion via issue #266.

**Closed by wrightaprilm** 2018-04-25 02:34 UTC
